/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * By contributing to this project, you agree to license your contributions
 * under the GPLv3 (or any later version) or any future licenses chosen by
 * the project author(s).
 *
 * Unicode character classes and case/accent folding for the ONNX embedding
 * tokenizer, matching the reference BERT BasicTokenizer (uncased).  Tables are
 * generated by scripts/gen_embed_unicode_tables.py; no Unicode library needed.
 */

#ifndef MEMORY_EMBED_UNICODE_H
#define MEMORY_EMBED_UNICODE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Most code points one character folds to. */
#define EMBED_FOLD_MAX 3

/** ASCII punctuation or any Unicode category P* character. */
bool embed_cp_is_punct(uint32_t cp);

/** Control/format character (Cc/Cf) other than tab, newline, CR: removed. */
bool embed_cp_is_control(uint32_t cp);

/** Tab, newline, CR, space or any Zs character: a word boundary. */
bool embed_cp_is_space(uint32_t cp);

/** CJK ideograph: tokenized as its own word. */
bool embed_cp_is_cjk(uint32_t cp);

/**
 * @brief Lowercase, NFD-decompose and strip combining marks from one character
 *
 * @param out Receives up to EMBED_FOLD_MAX code points
 * @return Number written (0 for a combining mark, which is dropped)
 */
int embed_cp_fold(uint32_t cp, uint32_t out[EMBED_FOLD_MAX]);

/**
 * @brief Decode one UTF-8 character
 *
 * Invalid or truncated sequences decode as U+FFFD and consume one byte.
 *
 * @return Bytes consumed (>= 1 while len > 0; 0 when len == 0)
 */
size_t embed_utf8_decode(const char *s, size_t len, uint32_t *cp_out);

/**
 * @brief Encode one code point as UTF-8
 *
 * @return Bytes written (1-4)
 */
int embed_utf8_encode(uint32_t cp, char out[4]);

#ifdef __cplusplus
}
#endif

#endif /* MEMORY_EMBED_UNICODE_H */
