#!/usr/bin/env bash

###############################################################################
# code_metrics.sh - reproducible size and code-health numbers for DAWN
#
# Prints Markdown:
#   - lines per area (cloc: code, comments, blank lines), first-party only
#   - function size and complexity in the daemon (lizard)
#   - duplicated code in the daemon (lizard's duplicate detector)
#   - files over the size limits (ARCHITECTURE.md, File Organization Standards)
#   - test counts
#
# Counts tracked files only, and leaves out vendored code (third_party/,
# www/js/vendor/), git submodules and generated files (a "generated" header
# naming the script that writes them).  Complexity is lizard's cyclomatic
# number: it counts each &&, || and case label, so it runs higher than tools
# that count only branches.
#
# Requires: git, cloc, lizard (pip install lizard).  The daemon pass takes
# about a minute.
#
# Usage:   ./scripts/code_metrics.sh [--build-dir DIR]
#          --build-dir DIR   also count the CI tests registered there (ctest -L ci)
###############################################################################

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BUILD_DIR=""
while [ $# -gt 0 ]; do
   case "$1" in
      --build-dir)
         BUILD_DIR="${2:-}"
         shift 2
         ;;
      -h | --help)
         sed -n '4,24p' "$0" | sed 's/^# \{0,1\}//'
         exit 0
         ;;
      *)
         echo "Unknown option: $1 (see --help)" >&2
         exit 2
         ;;
   esac
done

for tool in git cloc; do
   if ! command -v "$tool" > /dev/null; then
      echo "$tool not found" >&2
      exit 1
   fi
done
if command -v lizard > /dev/null; then
   LIZARD=(lizard)
elif python3 -m lizard --version > /dev/null 2>&1; then
   LIZARD=(python3 -m lizard)
else
   echo "lizard not found: pip install lizard" >&2
   exit 1
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Size limits (ARCHITECTURE.md, File Organization Standards): soft and hard.
C_SOFT=1500
C_HARD=2500
JS_SOFT=1000
JS_HARD=1500
CSS_SOFT=1000
CSS_HARD=2000

# Programming-language files that count as code, by extension.
CODE_EXT="c,h,cpp,hpp,cc,ino,js,mjs,css,html,py,sh,bash"

# ----------------------------------------------------------------------------
# File lists
# ----------------------------------------------------------------------------

# Tracked regular files (a submodule is tracked as a directory, so -f drops it).
git ls-files -z | while IFS= read -r -d '' f; do
   [ -f "$f" ] && printf '%s\n' "$f"
done > "$TMP/tracked"

grep -E '^(third_party|www/js/vendor)/' "$TMP/tracked" > "$TMP/vendored" || true

# A generated file says so in its header, naming its generator.
grep -vE '^(third_party|www/js/vendor)/' "$TMP/tracked" |
   xargs -d '\n' awk 'FNR <= 30 && /^[\/* #]*GENERATED by / { print FILENAME; nextfile }' \
      > "$TMP/generated" || true

grep -vE '^(third_party|www/js/vendor)/' "$TMP/tracked" | grep -vxF -f "$TMP/generated" \
   > "$TMP/first_party" || true

# ----------------------------------------------------------------------------
# Lines by area
# ----------------------------------------------------------------------------

# cloc totals for a file list: "files code comment blank".
cloc_totals() {
   if [ ! -s "$1" ]; then
      echo "0 0 0 0"
      return
   fi
   cloc --list-file="$1" --include-ext="$CODE_EXT" --csv --quiet 2> /dev/null |
      awk -F, 'NR > 1 && $2 != "SUM" { f += $1; b += $3; c += $4; k += $5 }
               END { printf "%d %d %d %d\n", f, k, c, b }'
}

AREAS=(
   "Daemon|^(src|include|common)/"
   "Tests|^tests/"
   "WebUI|^www/"
   "Satellites (Pi, ESP32)|^(dawn_satellite|dawn_satellite_arduino)/"
   "Admin CLI|^dawn-admin/"
   "Benchmarks|^(benchmarks|llm_testing)/"
   "Scripts and services|^(scripts|services)/"
)

echo "# DAWN code metrics"
echo
echo "Commit \`$(git rev-parse --short HEAD)\`, $(date -u +%Y-%m-%d). Reproduce with \`scripts/code_metrics.sh\`."
echo
echo "## Lines by area"
echo
echo "First-party code only (C/C++, JavaScript, CSS, HTML, Python, shell)."
echo
echo "| Area | Files | Code | Comments | Blank |"
echo "|---|---:|---:|---:|---:|"
total_f=0 total_k=0 total_c=0 total_b=0
for entry in "${AREAS[@]}"; do
   name="${entry%%|*}"
   pattern="${entry#*|}"
   grep -E "$pattern" "$TMP/first_party" > "$TMP/area" || true
   read -r f k c b < <(cloc_totals "$TMP/area")
   printf '| %s | %d | %d | %d | %d |\n' "$name" "$f" "$k" "$c" "$b"
   total_f=$((total_f + f)) total_k=$((total_k + k))
   total_c=$((total_c + c)) total_b=$((total_b + b))
done
printf '| **Total** | **%d** | **%d** | **%d** | **%d** |\n' \
   "$total_f" "$total_k" "$total_c" "$total_b"
read -r f k c b < <(cloc_totals "$TMP/vendored")
generated="$(sed 's/.*/`&`/' "$TMP/generated" | paste -sd, - | sed 's/,/, /g')"
echo
echo "Not counted: vendored code, $f files / $k code lines (\`third_party/\`," \
   "\`www/js/vendor/\`); generated files (${generated:-none}); git submodules."

# ----------------------------------------------------------------------------
# Daemon functions and duplication (one lizard pass)
# ----------------------------------------------------------------------------

grep -E '^(src|common)/.*\.(c|cpp|h|hpp)$' "$TMP/first_party" > "$TMP/daemon_src" || true
xargs -d '\n' "${LIZARD[@]}" --csv -Eduplicate < "$TMP/daemon_src" > "$TMP/lizard" 2> /dev/null || true

# CSV rows: NLOC,CCN,tokens,params,length,"location","file","name",...
grep -E '^[0-9]+,[0-9]+,' "$TMP/lizard" > "$TMP/functions" || true
dup_rate="$(grep -oE 'Total duplicate rate: [0-9.]+%' "$TMP/lizard" | grep -oE '[0-9.]+%' || echo "n/a")"

fn_count="$(wc -l < "$TMP/functions")"
median_len="$(cut -d, -f5 "$TMP/functions" | sort -n | awk -v m=$(((fn_count + 1) / 2)) 'NR == m')"

echo
echo "## Daemon functions (\`src/\`, \`common/\`)"
echo
awk -F, -v median="${median_len:-0}" '{
      n++; nloc += $1; ccn += $2
      if ($2 >= 20) c20++
      if ($2 >= 50) c50++
      if ($5 > 150) l150++
      if ($4 >= 8) p8++
   }
   END {
      if (n == 0) { print "No functions found."; exit }
      printf "| Measure | Value |\n|---|---:|\n"
      printf "| Functions | %d |\n", n
      printf "| Mean length (code lines) | %.1f |\n", nloc / n
      printf "| Median length (lines) | %d |\n", median
      printf "| Mean cyclomatic complexity | %.1f |\n", ccn / n
      printf "| Complexity >= 20 | %d (%.1f%%) |\n", c20, 100 * c20 / n
      printf "| Complexity >= 50 | %d (%.1f%%) |\n", c50, 100 * c50 / n
      printf "| Longer than 150 lines | %d (%.1f%%) |\n", l150, 100 * l150 / n
      printf "| 8 or more parameters | %d (%.1f%%) |\n", p8, 100 * p8 / n
   }' "$TMP/functions"
echo "| Duplicated code (lizard) | $dup_rate |"

echo
echo "Most complex functions:"
echo
echo "| Function | File | Complexity | Lines |"
echo "|---|---|---:|---:|"
# awk, not head: head exits early and pipefail would end the script on sort's SIGPIPE.
sort -t, -k2,2nr "$TMP/functions" |
   awk -F, 'NR <= 10 { gsub(/"/, "", $7); gsub(/"/, "", $8); printf "| `%s` | `%s` | %d | %d |\n", $8, $7, $2, $5 }'

# ----------------------------------------------------------------------------
# Files over the size limits
# ----------------------------------------------------------------------------

echo
echo "## Files over the size limits"
echo
echo "Physical lines. Limits (soft / hard): C and C++ $C_SOFT / $C_HARD," \
   "JavaScript $JS_SOFT / $JS_HARD, CSS $CSS_SOFT / $CSS_HARD."
echo
grep -E '\.(c|cpp|js|css)$' "$TMP/first_party" | xargs -d '\n' wc -l | grep -v ' total$' |
   awk -v cs="$C_SOFT" -v ch="$C_HARD" -v js="$JS_SOFT" -v jh="$JS_HARD" \
      -v ss="$CSS_SOFT" -v sh="$CSS_HARD" '{
      n = $1; f = $2
      if (f ~ /\.(c|cpp)$/) { soft = cs; hard = ch; kind = "C/C++" }
      else if (f ~ /\.js$/) { soft = js; hard = jh; kind = "JavaScript" }
      else { soft = ss; hard = sh; kind = "CSS" }
      if (n > hard) { over[kind]++; list = list sprintf("| `%s` | %d |\n", f, n) }
      else if (n > soft) soft_only[kind]++
   }
   END {
      printf "| Kind | Over soft only | Over hard |\n|---|---:|---:|\n"
      split("C/C++ JavaScript CSS", kinds, " ")
      for (i = 1; i <= 3; i++) printf "| %s | %d | %d |\n", kinds[i], soft_only[kinds[i]], over[kinds[i]]
      if (list != "") printf "\nOver the hard limit:\n\n| File | Lines |\n|---|---:|\n%s", list
   }'

# ----------------------------------------------------------------------------
# Tests
# ----------------------------------------------------------------------------

grep -E '^tests/.*\.c$' "$TMP/first_party" > "$TMP/test_src" || true
test_files="$(wc -l < "$TMP/test_src")"
# grep exits 1 on no match; count that as 0 rather than ending the script.
test_fns="$({ xargs -d '\n' grep -hE '^(static )?void test_[A-Za-z0-9_]*\(void\)' < "$TMP/test_src" ||
   true; } | wc -l)"
asserts="$({ xargs -d '\n' grep -ohE '\bTEST_ASSERT[A-Z0-9_]*\b' < "$TMP/test_src" || true; } | wc -l)"

echo
echo "## Tests"
echo
echo "| Measure | Value |"
echo "|---|---:|"
echo "| Test source files | $test_files |"
echo "| Test functions | $test_fns |"
echo "| Assertions (\`TEST_ASSERT*\`) | $asserts |"
if [ -n "$BUILD_DIR" ]; then
   ci_tests="$(ctest --test-dir "$BUILD_DIR" -N -L ci 2> /dev/null | grep -oE 'Total Tests: [0-9]+' |
      grep -oE '[0-9]+' || echo "n/a")"
   echo "| CI suites registered in \`$BUILD_DIR\` (\`ctest -L ci\`) | $ci_tests |"
fi
