#!/usr/bin/env python3
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.  Distributed WITHOUT ANY WARRANTY; see <https://www.gnu.org/licenses/>.
"""Generate src/memory/memory_embed_unicode_tables.inc.

The ONNX embedding tokenizer must pre-tokenize exactly like the reference BERT
BasicTokenizer (uncased), which relies on Python's unicodedata:
  - control characters (Cc/Cf, except tab/newline/CR) are removed;
  - whitespace (tab/newline/CR/space and category Zs) becomes a space;
  - each character is lowercased, NFD-decomposed, and stripped of combining
    marks (Mn);
  - punctuation is ASCII punctuation or any category P* character;
  - CJK ideographs are surrounded by spaces (ranges are fixed in the C code).

This script emits those tables so the C tokenizer needs no Unicode library.
Hangul syllables are handled algorithmically in C and excluded here.

Usage:  python3 scripts/gen_embed_unicode_tables.py > src/memory/memory_embed_unicode_tables.inc
"""
import sys
import unicodedata



# Every generated source file carries the project's license notice.
GPL_HEADER = [
    "This program is free software: you can redistribute it and/or modify",
    "it under the terms of the GNU General Public License as published by",
    "the Free Software Foundation, either version 3 of the License, or",
    "(at your option) any later version.",
    "",
    "This program is distributed in the hope that it will be useful,",
    "but WITHOUT ANY WARRANTY; without even the implied warranty of",
    "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the",
    "GNU General Public License for more details.",
    "",
    "You should have received a copy of the GNU General Public License",
    "along with this program.  If not, see <https://www.gnu.org/licenses/>.",
    "",
    "By contributing to this project, you agree to license your contributions",
    "under the GPLv3 (or any later version) or any future licenses chosen by",
    "the project author(s).",
]

def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = not (0xD800 <= cp <= 0xDFFF) and pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def cat(cp):
    return unicodedata.category(chr(cp))


def fold(c):
    """lower -> NFD -> drop Mn, per character (the reference order)."""
    s = unicodedata.normalize("NFD", c.lower())
    return "".join(x for x in s if unicodedata.category(x) != "Mn")


def emit_ranges(name, rs):
    print(f"static const embed_cp_range_t {name}[] = {{")
    for a, b in rs:
        print(f"   {{ 0x{a:05X}, 0x{b:05X} }},")
    print("};")


def main():
    print("/*")
    for line in GPL_HEADER:
        print(" *" + (" " + line if line else ""))
    print(" */")
    print()
    print("/* GENERATED by scripts/gen_embed_unicode_tables.py from Python "
          f"{sys.version.split()[0]} unicodedata {unicodedata.unidata_version}.")
    print(" * Do not edit by hand; re-run the script instead. */")
    print()
    ascii_punct = lambda cp: (33 <= cp <= 47) or (58 <= cp <= 64) or (91 <= cp <= 96) or (123 <= cp <= 126)
    emit_ranges("k_punct", ranges(lambda cp: ascii_punct(cp) or cat(cp).startswith("P")))
    print()
    emit_ranges("k_control",
                ranges(lambda cp: cat(cp) in ("Cc", "Cf") and cp not in (9, 10, 13)))
    print()
    emit_ranges("k_space", ranges(lambda cp: cp in (9, 10, 13, 32) or cat(cp) == "Zs"))
    print()
    emit_ranges("k_mark", ranges(lambda cp: cat(cp) == "Mn"))
    print()
    print("static const embed_cp_map_t k_fold[] = {")
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF or 0xAC00 <= cp <= 0xD7A3 or cat(cp) == "Mn":
            continue
        c = chr(cp)
        r = fold(c)
        if r != c:
            assert 1 <= len(r) <= 3, (hex(cp), r)
            outs = ", ".join(f"0x{ord(x):05X}" for x in r) + ", 0" * (3 - len(r))
            print(f"   {{ 0x{cp:05X}, {len(r)}, {{ {outs} }} }},")
    print("};")


if __name__ == "__main__":
    main()
